
jobs:
- job: Cypress_e2e_tests
  pool:
    vmImage: 'macos-latest'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: CacheBeta@1
      inputs:
        key: npm | $(Agent.OS) | package-lock.json
        path: /home/vsts/.npm
        restoreKeys: npm | $(Agent.OS) | package-lock.json
      displayName: Cache NPM packages

 

    - script: npm ci
      displayName: 'Install NPM dependencies'

    - script: npm run smoke








